[supabase]
SUPABASE_URL="https://xvvoseasdhnuiujjvhwt.supabase.co"
SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2dm9zZWFzZGhudWl1amp2aHd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQxODk2MjQsImV4cCI6MjA3OTc2NTYyNH0.ahlVgCGFR-PSbp3Rz495iq2trgXKMZvwNeXbIWfUkNA"
